/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      /* ── Colors ──────────────────────────────── */
      colors: {
        /* Primitives — full palette */
        grey: {
          25: 'var(--color-grey-25)',
          50: 'var(--color-grey-50)',
          100: 'var(--color-grey-100)',
          200: 'var(--color-grey-200)',
          300: 'var(--color-grey-300)',
          400: 'var(--color-grey-400)',
          500: 'var(--color-grey-500)',
          600: 'var(--color-grey-600)',
          700: 'var(--color-grey-700)',
          800: 'var(--color-grey-800)',
          900: 'var(--color-grey-900)',
        },
        green: {
          25: 'var(--color-green-25)',
          50: 'var(--color-green-50)',
          100: 'var(--color-green-100)',
          200: 'var(--color-green-200)',
          300: 'var(--color-green-300)',
          400: 'var(--color-green-400)',
          500: 'var(--color-green-500)',
          600: 'var(--color-green-600)',
          700: 'var(--color-green-700)',
          800: 'var(--color-green-800)',
          900: 'var(--color-green-900)',
        },
        orange: {
          25: 'var(--color-orange-25)',
          50: 'var(--color-orange-50)',
          100: 'var(--color-orange-100)',
          200: 'var(--color-orange-200)',
          300: 'var(--color-orange-300)',
          400: 'var(--color-orange-400)',
          500: 'var(--color-orange-500)',
          600: 'var(--color-orange-600)',
          700: 'var(--color-orange-700)',
          800: 'var(--color-orange-800)',
          900: 'var(--color-orange-900)',
        },
        red: {
          25: 'var(--color-red-25)',
          50: 'var(--color-red-50)',
          100: 'var(--color-red-100)',
          200: 'var(--color-red-200)',
          300: 'var(--color-red-300)',
          400: 'var(--color-red-400)',
          500: 'var(--color-red-500)',
          600: 'var(--color-red-600)',
          700: 'var(--color-red-700)',
          800: 'var(--color-red-800)',
          900: 'var(--color-red-900)',
        },
        blue: {
          25: 'var(--color-blue-25)',
          50: 'var(--color-blue-50)',
          100: 'var(--color-blue-100)',
          200: 'var(--color-blue-200)',
          300: 'var(--color-blue-300)',
          400: 'var(--color-blue-400)',
          500: 'var(--color-blue-500)',
          600: 'var(--color-blue-600)',
          700: 'var(--color-blue-700)',
          800: 'var(--color-blue-800)',
          900: 'var(--color-blue-900)',
        },
        teal: {
          25: 'var(--color-teal-25)',
          50: 'var(--color-teal-50)',
          100: 'var(--color-teal-100)',
          200: 'var(--color-teal-200)',
          300: 'var(--color-teal-300)',
          400: 'var(--color-teal-400)',
          500: 'var(--color-teal-500)',
          600: 'var(--color-teal-600)',
          700: 'var(--color-teal-700)',
          800: 'var(--color-teal-800)',
          900: 'var(--color-teal-900)',
        },
        'light-green': {
          25: 'var(--color-light-green-25)',
          50: 'var(--color-light-green-50)',
          100: 'var(--color-light-green-100)',
          200: 'var(--color-light-green-200)',
          300: 'var(--color-light-green-300)',
          400: 'var(--color-light-green-400)',
          500: 'var(--color-light-green-500)',
          600: 'var(--color-light-green-600)',
          700: 'var(--color-light-green-700)',
          800: 'var(--color-light-green-800)',
          900: 'var(--color-light-green-900)',
        },
        yellow: {
          25: 'var(--color-yellow-25)',
          50: 'var(--color-yellow-50)',
          100: 'var(--color-yellow-100)',
          200: 'var(--color-yellow-200)',
          300: 'var(--color-yellow-300)',
          400: 'var(--color-yellow-400)',
          500: 'var(--color-yellow-500)',
          600: 'var(--color-yellow-600)',
          700: 'var(--color-yellow-700)',
          800: 'var(--color-yellow-800)',
          900: 'var(--color-yellow-900)',
        },
        pink: {
          25: 'var(--color-pink-25)',
          50: 'var(--color-pink-50)',
          100: 'var(--color-pink-100)',
          200: 'var(--color-pink-200)',
          300: 'var(--color-pink-300)',
          400: 'var(--color-pink-400)',
          500: 'var(--color-pink-500)',
          600: 'var(--color-pink-600)',
          700: 'var(--color-pink-700)',
          800: 'var(--color-pink-800)',
          900: 'var(--color-pink-900)',
        },
        purple: {
          25: 'var(--color-purple-25)',
          50: 'var(--color-purple-50)',
          100: 'var(--color-purple-100)',
          200: 'var(--color-purple-200)',
          300: 'var(--color-purple-300)',
          400: 'var(--color-purple-400)',
          500: 'var(--color-purple-500)',
          600: 'var(--color-purple-600)',
          700: 'var(--color-purple-700)',
          800: 'var(--color-purple-800)',
          900: 'var(--color-purple-900)',
        },
        'dark-blue': {
          25: 'var(--color-dark-blue-25)',
          50: 'var(--color-dark-blue-50)',
          100: 'var(--color-dark-blue-100)',
          200: 'var(--color-dark-blue-200)',
          300: 'var(--color-dark-blue-300)',
          400: 'var(--color-dark-blue-400)',
          500: 'var(--color-dark-blue-500)',
          600: 'var(--color-dark-blue-600)',
          700: 'var(--color-dark-blue-700)',
          800: 'var(--color-dark-blue-800)',
          900: 'var(--color-dark-blue-900)',
        },

        /* Semantic aliases */
        primary: {
          DEFAULT: 'var(--color-primary)',
          hover: 'var(--color-primary-hover)',
          active: 'var(--color-primary-active)',
          light: 'var(--color-primary-light)',
          foreground: 'var(--color-primary-foreground)',
        },
        secondary: {
          DEFAULT: 'var(--color-secondary)',
          hover: 'var(--color-secondary-hover)',
          light: 'var(--color-secondary-light)',
          foreground: 'var(--color-secondary-foreground)',
        },
        background: 'var(--color-background)',
        'background-subtle': 'var(--color-background-subtle)',
        surface: {
          DEFAULT: 'var(--color-surface)',
          raised: 'var(--color-surface-raised)',
          overlay: 'var(--color-surface-overlay)',
        },
        foreground: 'var(--color-text)',
        'text-secondary': 'var(--color-text-secondary)',
        'text-tertiary': 'var(--color-text-tertiary)',
        'text-placeholder': 'var(--color-text-placeholder)',
        'text-disabled': 'var(--color-text-disabled)',
        border: 'var(--color-border)',
        'border-hover': 'var(--color-border-hover)',
        input: 'var(--color-input)',
        ring: 'var(--color-ring)',
        muted: {
          DEFAULT: 'var(--color-muted)',
          foreground: 'var(--color-muted-foreground)',
        },
        destructive: {
          DEFAULT: 'var(--color-error)',
          light: 'var(--color-error-light)',
          foreground: 'var(--color-error-foreground)',
        },
        success: {
          DEFAULT: 'var(--color-success)',
          light: 'var(--color-success-light)',
          foreground: 'var(--color-success-foreground)',
        },
        warning: {
          DEFAULT: 'var(--color-warning)',
          light: 'var(--color-warning-light)',
          foreground: 'var(--color-warning-foreground)',
        },
        info: {
          DEFAULT: 'var(--color-info)',
          light: 'var(--color-info-light)',
          foreground: 'var(--color-info-foreground)',
        },
      },

      /* ── Font Family ─────────────────────────── */
      fontFamily: {
        sans: ['var(--font-family-base)'],
      },

      /* ── Font Size ───────────────────────────── */
      fontSize: {
        'xxs': ['var(--font-size-xxs)', { lineHeight: 'var(--line-height-xxs)' }],
        'xs': ['var(--font-size-xs)', { lineHeight: 'var(--line-height-xs)' }],
        'sm': ['var(--font-size-sm)', { lineHeight: 'var(--line-height-sm)' }],
        'base': ['var(--font-size-md)', { lineHeight: 'var(--line-height-md)' }],
        'lg': ['var(--font-size-lg)', { lineHeight: 'var(--line-height-lg)' }],
        'xl': ['var(--font-size-xl)', { lineHeight: 'var(--line-height-xl)' }],
        'h-xs': ['var(--font-size-h-xs)', { lineHeight: 'var(--line-height-h-xs)', letterSpacing: 'var(--letter-spacing-normal)' }],
        'h-sm': ['var(--font-size-h-sm)', { lineHeight: 'var(--line-height-h-sm)', letterSpacing: 'var(--letter-spacing-normal)' }],
        'h-md': ['var(--font-size-h-md)', { lineHeight: 'var(--line-height-h-md)', letterSpacing: 'var(--letter-spacing-tight-sm)' }],
        'h-lg': ['var(--font-size-h-lg)', { lineHeight: 'var(--line-height-h-lg)', letterSpacing: 'var(--letter-spacing-tight-md)' }],
        'h-xl': ['var(--font-size-h-xl)', { lineHeight: 'var(--line-height-h-xl)', letterSpacing: 'var(--letter-spacing-tight-lg)' }],
        'h-xxl': ['var(--font-size-h-xxl)', { lineHeight: 'var(--line-height-h-xxl)', letterSpacing: 'var(--letter-spacing-tight-xl)' }],
      },

      /* ── Font Weight ─────────────────────────── */
      fontWeight: {
        normal: 'var(--font-weight-regular)',
        medium: 'var(--font-weight-medium)',
        semibold: 'var(--font-weight-semibold)',
        bold: 'var(--font-weight-bold)',
      },

      /* ── Spacing (extend, not override) ──────── */
      spacing: {
        '0.5': 'var(--spacing-0-5)',
        '1': 'var(--spacing-1)',
        '1.5': 'var(--spacing-1-5)',
        '2': 'var(--spacing-2)',
        '2.5': 'var(--spacing-2-5)',
        '3': 'var(--spacing-3)',
        '3.5': 'var(--spacing-3-5)',
        '4': 'var(--spacing-4)',
        '5': 'var(--spacing-5)',
        '6': 'var(--spacing-6)',
        '7': 'var(--spacing-7)',
        '8': 'var(--spacing-8)',
        '9': 'var(--spacing-9)',
        '10': 'var(--spacing-10)',
        '12': 'var(--spacing-12)',
        '14': 'var(--spacing-14)',
        '16': 'var(--spacing-16)',
        '20': 'var(--spacing-20)',
        '24': 'var(--spacing-24)',
      },

      /* ── Border Radius ──────────────────────── */
      borderRadius: {
        none: 'var(--radius-none)',
        sm: 'var(--radius-sm)',
        DEFAULT: 'var(--radius-md)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        '2xl': 'var(--radius-2xl)',
        '3xl': 'var(--radius-3xl)',
        full: 'var(--radius-full)',
      },

      /* ── Shadows ────────────────────────────── */
      boxShadow: {
        xs: 'var(--shadow-xs)',
        sm: 'var(--shadow-sm)',
        DEFAULT: 'var(--shadow-md)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
        xl: 'var(--shadow-xl)',
        '2xl': 'var(--shadow-2xl)',
        '3xl': 'var(--shadow-3xl)',
      },
    },
  },
  plugins: [],
};
