const nodemailer = require('nodemailer');

let transporter = null;

function getTransporter() {
  if (transporter) return transporter;

  const host = process.env.SMTP_HOST;
  if (!host) return null;

  transporter = nodemailer.createTransport({
    host,
    port: parseInt(process.env.SMTP_PORT || '587', 10),
    secure: process.env.SMTP_PORT === '465',
    auth: {
      user: process.env.SMTP_USER,
      pass: process.env.SMTP_PASS,
    },
  });

  return transporter;
}

/**
 * Send a report email with optional file attachments.
 *
 * @param {object} opts
 * @param {string[]} opts.to - Recipient email addresses
 * @param {string} opts.reportType - e.g. "RPT-01"
 * @param {string} opts.reportName - Human-readable report name
 * @param {string} opts.period - e.g. "01 Jan 2026 – 31 Mar 2026"
 * @param {{ filename: string, path: string }[]} opts.attachments
 * @returns {Promise<{ sent: boolean, messageId?: string, reason?: string }>}
 */
async function sendReportEmail({ to, reportType, reportName, period, attachments }) {
  const smtp = getTransporter();
  if (!smtp) {
    console.warn('[EmailService] SMTP not configured — skipping email delivery');
    return { sent: false, reason: 'SMTP not configured' };
  }

  const from = process.env.SMTP_FROM || 'noreply@statice.nl';
  const subject = `Statice MRF — ${reportName} — ${period}`;
  const text = [
    `Please find attached the ${reportName} for ${period}.`,
    '',
    `Generated by the Statice MRF Management System on ${new Date().toISOString()}.`,
    '',
    'This is an automated report. Do not reply to this email.',
  ].join('\n');

  try {
    const info = await smtp.sendMail({
      from,
      to: Array.isArray(to) ? to.join(', ') : to,
      subject,
      text,
      attachments: (attachments || []).map((a) => ({ filename: a.filename, path: a.path })),
    });
    return { sent: true, messageId: info.messageId };
  } catch (err) {
    console.error('[EmailService] Failed to send email:', err.message);
    return { sent: false, reason: err.message };
  }
}

module.exports = { sendReportEmail };
