const ExcelJS = require('exceljs');

// Header fill color — grey-50 from design tokens
const HEADER_FILL = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF9FAFB' } };
const TOTALS_FILL = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFECFDF5' } };
const THIN_BORDER = { style: 'thin', color: { argb: 'FFE4E7EC' } };
const ALL_BORDERS = { top: THIN_BORDER, bottom: THIN_BORDER, left: THIN_BORDER, right: THIN_BORDER };

function createWorkbook() {
  const wb = new ExcelJS.Workbook();
  wb.creator = 'Statice MRF';
  wb.created = new Date();
  return wb;
}

function styleHeaderRow(ws, rowNum) {
  const row = ws.getRow(rowNum);
  row.eachCell((cell) => {
    cell.fill = HEADER_FILL;
    cell.font = { bold: true, size: 10 };
    cell.border = ALL_BORDERS;
    cell.alignment = { vertical: 'middle' };
  });
  row.height = 24;
}

function styleDataRow(ws, rowNum) {
  const row = ws.getRow(rowNum);
  row.eachCell((cell) => {
    cell.border = ALL_BORDERS;
    cell.font = { size: 10 };
    cell.alignment = { vertical: 'middle' };
  });
}

function styleTotalsRow(ws, rowNum) {
  const row = ws.getRow(rowNum);
  row.eachCell((cell) => {
    cell.fill = TOTALS_FILL;
    cell.font = { bold: true, size: 10 };
    cell.border = ALL_BORDERS;
    cell.alignment = { vertical: 'middle' };
  });
  row.height = 24;
}

function addInfoSheet(wb, { title, period, generatedBy, generatedAt }) {
  const ws = wb.addWorksheet('Report Info');
  ws.columns = [{ width: 25 }, { width: 50 }];
  ws.addRow(['STATICE B.V.', '']).font = { bold: true, size: 14 };
  ws.addRow(['E-Waste Material Recovery Facility', '']);
  ws.addRow([]);
  ws.addRow(['Report', title]);
  if (period) {
    ws.addRow(['Period From', period.from]);
    ws.addRow(['Period To', period.to]);
  }
  ws.addRow(['Generated By', generatedBy || 'System']);
  ws.addRow(['Generated At', (generatedAt || new Date()).toISOString()]);
  ws.addRow(['Facility', 'Statice B.V.']);
  ws.addRow(['Permit', 'ST-2026-001']);
  ws.addRow([]);
  ws.addRow(['SIMULATED WEIGHING DATA — NOT FOR REGULATORY USE']);
}

function formatWeight(kg) {
  return Math.round((Number(kg) || 0) * 100) / 100;
}

function formatPct(pct) {
  return Math.round((Number(pct) || 0) * 100) / 100;
}

/* ───── RPT-01: Supplier Statement ───── */

async function generateSupplierStatementXLSX(data, filePath, user) {
  const wb = createWorkbook();
  addInfoSheet(wb, { title: 'Supplier Circularity Statement', period: data.period, generatedBy: user?.full_name });

  // Summary sheet
  const ws = wb.addWorksheet('Summary');
  ws.columns = [
    { header: 'Order Ref', key: 'orderNumber', width: 18 },
    { header: 'Delivery Date', key: 'plannedDate', width: 15 },
    { header: 'Carrier', key: 'carrierName', width: 22 },
    { header: 'Vehicle', key: 'vehiclePlates', width: 18 },
    { header: 'Net Weight (kg)', key: 'netWeightKg', width: 16 },
  ];
  styleHeaderRow(ws, 1);
  let rowNum = 2;
  for (const o of data.orders) {
    ws.addRow({
      orderNumber: o.orderNumber,
      plannedDate: o.plannedDate,
      carrierName: o.carrierName,
      vehiclePlates: (o.vehiclePlates || []).join(', '),
      netWeightKg: formatWeight(o.netWeightKg),
    });
    styleDataRow(ws, rowNum++);
  }
  ws.addRow({ orderNumber: 'TOTAL', netWeightKg: formatWeight(data.totals.totalNetWeightKg) });
  styleTotalsRow(ws, rowNum);

  // Category Detail sheet
  const cs = wb.addWorksheet('Category Detail');
  cs.columns = [
    { header: 'CBS Code', key: 'codeCbs', width: 14 },
    { header: 'Category', key: 'descriptionEn', width: 30 },
    { header: 'Waste Stream', key: 'wasteStream', width: 18 },
    { header: 'Net Weight (kg)', key: 'totalNetWeightKg', width: 16 },
    { header: 'Recycled %', key: 'recycledPct', width: 12 },
    { header: 'Reused %', key: 'reusedPct', width: 12 },
    { header: 'Disposed %', key: 'disposedPct', width: 12 },
    { header: 'Landfill %', key: 'landfillPct', width: 12 },
    { header: 'Processors', key: 'processors', width: 30 },
  ];
  styleHeaderRow(cs, 1);
  rowNum = 2;
  for (const c of data.categories) {
    cs.addRow({
      codeCbs: c.codeCbs,
      descriptionEn: c.descriptionEn,
      wasteStream: c.wasteStream,
      totalNetWeightKg: formatWeight(c.totalNetWeightKg),
      recycledPct: formatPct(c.weightedAvgRecycledPct),
      reusedPct: formatPct(c.weightedAvgReusedPct),
      disposedPct: formatPct(c.weightedAvgDisposedPct),
      landfillPct: formatPct(c.weightedAvgLandfillPct),
      processors: c.downstreamProcessors.join(', '),
    });
    styleDataRow(cs, rowNum++);
  }
  cs.addRow({
    codeCbs: 'TOTAL', totalNetWeightKg: formatWeight(data.totals.totalNetWeightKg),
    recycledPct: formatPct(data.totals.weightedAvgRecycledPct),
    reusedPct: formatPct(data.totals.weightedAvgReusedPct),
    disposedPct: formatPct(data.totals.weightedAvgDisposedPct),
    landfillPct: formatPct(data.totals.weightedAvgLandfillPct),
  });
  styleTotalsRow(cs, rowNum);

  await wb.xlsx.writeFile(filePath);
}

/* ───── RPT-02: Material Recovery Summary ───── */

async function generateMaterialRecoveryXLSX(data, filePath, user) {
  const wb = createWorkbook();
  addInfoSheet(wb, { title: 'Material Recovery Summary', period: data.period, generatedBy: user?.full_name });

  const ws = wb.addWorksheet('Recovery Summary');
  ws.columns = [
    { header: 'CBS Code', key: 'codeCbs', width: 14 },
    { header: 'Category', key: 'descriptionEn', width: 30 },
    { header: 'Inbound (kg)', key: 'totalInboundKg', width: 14 },
    { header: 'Recycled (kg)', key: 'recycledKg', width: 14 },
    { header: 'Recycled %', key: 'recycledPct', width: 12 },
    { header: 'Reused (kg)', key: 'reusedKg', width: 14 },
    { header: 'Reused %', key: 'reusedPct', width: 12 },
    { header: 'Disposed (kg)', key: 'disposedKg', width: 14 },
    { header: 'Disposed %', key: 'disposedPct', width: 12 },
    { header: 'Landfill (kg)', key: 'landfillKg', width: 14 },
    { header: 'Landfill %', key: 'landfillPct', width: 12 },
  ];
  styleHeaderRow(ws, 1);
  let rowNum = 2;
  for (const c of data.categories) {
    ws.addRow({
      codeCbs: c.codeCbs, descriptionEn: c.descriptionEn,
      totalInboundKg: formatWeight(c.totalInboundKg),
      recycledKg: formatWeight(c.recycledKg), recycledPct: formatPct(c.recycledPct),
      reusedKg: formatWeight(c.reusedKg), reusedPct: formatPct(c.reusedPct),
      disposedKg: formatWeight(c.disposedKg), disposedPct: formatPct(c.disposedPct),
      landfillKg: formatWeight(c.landfillKg), landfillPct: formatPct(c.landfillPct),
    });
    styleDataRow(ws, rowNum++);
  }
  ws.addRow({
    codeCbs: 'TOTAL',
    totalInboundKg: formatWeight(data.totals.totalInboundKg),
    recycledKg: formatWeight(data.totals.recycledKg), recycledPct: formatPct(data.totals.recycledPct),
    reusedKg: formatWeight(data.totals.reusedKg), reusedPct: formatPct(data.totals.reusedPct),
    disposedKg: formatWeight(data.totals.disposedKg), disposedPct: formatPct(data.totals.disposedPct),
    landfillKg: formatWeight(data.totals.landfillKg), landfillPct: formatPct(data.totals.landfillPct),
  });
  styleTotalsRow(ws, rowNum);

  // Comparison sheet
  if (data.priorCategories) {
    const cs = wb.addWorksheet('Comparison');
    cs.columns = [
      { header: 'Category', key: 'descriptionEn', width: 30 },
      { header: 'Current (kg)', key: 'currentKg', width: 14 },
      { header: 'Prior (kg)', key: 'priorKg', width: 14 },
      { header: 'Change (kg)', key: 'changeKg', width: 14 },
      { header: 'Change %', key: 'changePct', width: 12 },
    ];
    styleHeaderRow(cs, 1);
    let cr = 2;
    for (const c of data.categories) {
      const prior = data.priorCategories.find((p) => p.categoryId === c.categoryId);
      const priorKg = prior ? prior.totalInboundKg : 0;
      const change = c.totalInboundKg - priorKg;
      cs.addRow({
        descriptionEn: c.descriptionEn,
        currentKg: formatWeight(c.totalInboundKg),
        priorKg: formatWeight(priorKg),
        changeKg: formatWeight(change),
        changePct: priorKg > 0 ? formatPct((change / priorKg) * 100) : 0,
      });
      styleDataRow(cs, cr++);
    }
  }

  await wb.xlsx.writeFile(filePath);
}

/* ───── RPT-03: Chain of Custody ───── */

async function generateChainOfCustodyXLSX(data, filePath, user) {
  const wb = createWorkbook();
  addInfoSheet(wb, { title: 'Chain of Custody Report', generatedBy: user?.full_name });

  const ws = wb.addWorksheet('Consignments');
  ws.columns = [
    { header: 'Order #', key: 'orderNumber', width: 16 },
    { header: 'Date', key: 'date', width: 14 },
    { header: 'Carrier', key: 'carrier', width: 20 },
    { header: 'Supplier', key: 'supplier', width: 20 },
    { header: 'Vehicle', key: 'vehicle', width: 14 },
    { header: 'Asset Label', key: 'assetLabel', width: 14 },
    { header: 'Skip Type', key: 'skipType', width: 12 },
    { header: 'CBS Code', key: 'codeCbs', width: 12 },
    { header: 'Category', key: 'category', width: 24 },
    { header: 'Weight (kg)', key: 'weight', width: 12 },
    { header: 'Recycled %', key: 'recycledPct', width: 10 },
    { header: 'Reused %', key: 'reusedPct', width: 10 },
    { header: 'Disposed %', key: 'disposedPct', width: 10 },
    { header: 'Landfill %', key: 'landfillPct', width: 10 },
    { header: 'Processor', key: 'processor', width: 24 },
  ];
  styleHeaderRow(ws, 1);
  let rowNum = 2;
  for (const c of data.consignments) {
    for (const event of c.inboundsData) {
      for (const asset of event.assets) {
        if (asset.sortingLines.length === 0) {
          ws.addRow({
            orderNumber: c.orderNumber, date: c.plannedDate, carrier: c.carrier.name,
            supplier: c.supplier.name, vehicle: event.vehiclePlate,
            assetLabel: asset.assetLabel, skipType: asset.skipType,
            codeCbs: asset.category, category: asset.categoryDescription,
            weight: formatWeight(asset.netWeightKg),
          });
          styleDataRow(ws, rowNum++);
        }
        for (const line of asset.sortingLines) {
          ws.addRow({
            orderNumber: c.orderNumber, date: c.plannedDate, carrier: c.carrier.name,
            supplier: c.supplier.name, vehicle: event.vehiclePlate,
            assetLabel: asset.assetLabel, skipType: asset.skipType,
            codeCbs: line.codeCbs, category: line.descriptionEn,
            weight: formatWeight(line.netWeightKg),
            recycledPct: formatPct(line.recycledPct), reusedPct: formatPct(line.reusedPct),
            disposedPct: formatPct(line.disposedPct), landfillPct: formatPct(line.landfillPct),
            processor: line.downstreamProcessor || '',
          });
          styleDataRow(ws, rowNum++);
        }
      }
    }
  }

  await wb.xlsx.writeFile(filePath);
}

/* ───── RPT-04: Inbound Weight Register ───── */

async function generateInboundWeightRegisterXLSX(data, filePath, user) {
  const wb = createWorkbook();
  addInfoSheet(wb, { title: 'Inbound Weight Register', period: data.period, generatedBy: user?.full_name });

  // All events
  const ws = wb.addWorksheet('All Events');
  ws.columns = [
    { header: 'Date/Time', key: 'arrivedAt', width: 18 },
    { header: 'Order #', key: 'orderNumber', width: 16 },
    { header: 'Supplier', key: 'supplierName', width: 20 },
    { header: 'Carrier', key: 'carrierName', width: 20 },
    { header: 'Vehicle', key: 'vehiclePlate', width: 14 },
    { header: 'Skips', key: 'skipCount', width: 8 },
    { header: 'Gross (kg)', key: 'grossWeightKg', width: 14 },
    { header: 'Tare (kg)', key: 'tareWeightKg', width: 14 },
    { header: 'Net (kg)', key: 'netWeightKg', width: 14 },
    { header: 'Afvalstroomnummer', key: 'afvalstroomnummer', width: 18 },
  ];
  styleHeaderRow(ws, 1);
  let rowNum = 2;
  for (const e of data.events) {
    ws.addRow({
      arrivedAt: e.arrivedAt, orderNumber: e.orderNumber, supplierName: e.supplierName,
      carrierName: e.carrierName, vehiclePlate: e.vehiclePlate, skipCount: e.skipCount,
      grossWeightKg: formatWeight(e.grossWeightKg), tareWeightKg: formatWeight(e.tareWeightKg),
      netWeightKg: formatWeight(e.netWeightKg), afvalstroomnummer: e.afvalstroomnummer || '',
    });
    styleDataRow(ws, rowNum++);
  }
  ws.addRow({
    arrivedAt: 'GRAND TOTAL', skipCount: data.grandTotals.skipCount,
    grossWeightKg: formatWeight(data.grandTotals.grossKg),
    tareWeightKg: formatWeight(data.grandTotals.tareKg),
    netWeightKg: formatWeight(data.grandTotals.netKg),
  });
  styleTotalsRow(ws, rowNum);

  // By Carrier
  const cs = wb.addWorksheet('By Carrier');
  cs.columns = [
    { header: 'Carrier', key: 'name', width: 30 },
    { header: 'Events', key: 'eventCount', width: 10 },
    { header: 'Skips', key: 'skipCount', width: 10 },
    { header: 'Gross (kg)', key: 'grossKg', width: 14 },
    { header: 'Tare (kg)', key: 'tareKg', width: 14 },
    { header: 'Net (kg)', key: 'netKg', width: 14 },
  ];
  styleHeaderRow(cs, 1);
  let cr = 2;
  for (const c of data.subtotalsByCarrier) {
    cs.addRow({ name: c.name, eventCount: c.eventCount, skipCount: c.skipCount, grossKg: formatWeight(c.grossKg), tareKg: formatWeight(c.tareKg), netKg: formatWeight(c.netKg) });
    styleDataRow(cs, cr++);
  }

  // By Waste Stream
  const wss = wb.addWorksheet('By Waste Stream');
  wss.columns = [
    { header: 'Waste Stream', key: 'name', width: 30 },
    { header: 'Code', key: 'code', width: 14 },
    { header: 'Events', key: 'eventCount', width: 10 },
    { header: 'Skips', key: 'skipCount', width: 10 },
    { header: 'Net (kg)', key: 'netKg', width: 14 },
  ];
  styleHeaderRow(wss, 1);
  let wr = 2;
  for (const w of data.subtotalsByWasteStream) {
    wss.addRow({ name: w.name, code: w.code, eventCount: w.eventCount, skipCount: w.skipCount, netKg: formatWeight(w.netKg) });
    styleDataRow(wss, wr++);
  }

  await wb.xlsx.writeFile(filePath);
}

/* ───── RPT-05: Waste Stream Analysis ───── */

async function generateWasteStreamAnalysisXLSX(data, filePath, user) {
  const wb = createWorkbook();
  addInfoSheet(wb, { title: 'Waste Stream Analysis', period: data.period, generatedBy: user?.full_name });

  const ws = wb.addWorksheet('Stream Summary');
  ws.columns = [
    { header: 'Waste Stream', key: 'streamName', width: 24 },
    { header: 'Code', key: 'streamCode', width: 12 },
    { header: 'Inbound (kg)', key: 'totalInboundKg', width: 14 },
    { header: 'Recycled %', key: 'recycledPct', width: 12 },
    { header: 'Reused %', key: 'reusedPct', width: 12 },
    { header: 'Disposed %', key: 'disposedPct', width: 12 },
    { header: 'Landfill %', key: 'landfillPct', width: 12 },
  ];
  styleHeaderRow(ws, 1);
  let rowNum = 2;
  for (const s of data.wasteStreams) {
    ws.addRow({
      streamName: s.streamName, streamCode: s.streamCode,
      totalInboundKg: formatWeight(s.totals.totalInboundKg),
      recycledPct: formatPct(s.totals.recycledPct), reusedPct: formatPct(s.totals.reusedPct),
      disposedPct: formatPct(s.totals.disposedPct), landfillPct: formatPct(s.totals.landfillPct),
    });
    styleDataRow(ws, rowNum++);
  }

  // Per-stream detail sheets
  for (const s of data.wasteStreams) {
    const ds = wb.addWorksheet(s.streamCode.substring(0, 28));
    ds.columns = [
      { header: 'CBS Code', key: 'codeCbs', width: 14 },
      { header: 'Category', key: 'descriptionEn', width: 30 },
      { header: 'Inbound (kg)', key: 'totalInboundKg', width: 14 },
      { header: 'Recycled %', key: 'recycledPct', width: 12 },
      { header: 'Reused %', key: 'reusedPct', width: 12 },
      { header: 'Disposed %', key: 'disposedPct', width: 12 },
      { header: 'Landfill %', key: 'landfillPct', width: 12 },
    ];
    styleHeaderRow(ds, 1);
    let dr = 2;
    for (const c of s.categories) {
      ds.addRow({
        codeCbs: c.codeCbs, descriptionEn: c.descriptionEn,
        totalInboundKg: formatWeight(c.totalInboundKg),
        recycledPct: formatPct(c.recycledPct), reusedPct: formatPct(c.reusedPct),
        disposedPct: formatPct(c.disposedPct), landfillPct: formatPct(c.landfillPct),
      });
      styleDataRow(ds, dr++);
    }
  }

  await wb.xlsx.writeFile(filePath);
}

/* ───── RPT-06: Asset Utilisation ───── */

async function generateAssetUtilisationXLSX(data, filePath, user) {
  const wb = createWorkbook();
  addInfoSheet(wb, { title: 'Skip Asset Utilisation', period: data.period, generatedBy: user?.full_name });

  const ws = wb.addWorksheet('Summary');
  ws.columns = [{ width: 30 }, { width: 20 }];
  ws.addRow(['Total Skips', data.totalSkips]);
  ws.addRow(['Average per Event', data.avgPerEvent]);
  ws.addRow([]);

  // By type
  const startRow = ws.rowCount + 1;
  ws.addRow(['Skip Type', 'Count']);
  styleHeaderRow(ws, startRow);
  let rowNum = startRow + 1;
  for (const t of data.byType) {
    ws.addRow([t.type, t.count]);
    styleDataRow(ws, rowNum++);
  }

  ws.addRow([]);
  const topStart = ws.rowCount + 1;
  ws.addRow(['Asset Label', 'Usage Count']);
  styleHeaderRow(ws, topStart);
  rowNum = topStart + 1;
  for (const a of data.topAssets) {
    ws.addRow([a.label, a.count]);
    styleDataRow(ws, rowNum++);
  }

  await wb.xlsx.writeFile(filePath);
}

/* ───── RPT-07: Downstream Material Statement ───── */

async function generateDownstreamStatementXLSX(data, filePath, user) {
  const wb = createWorkbook();
  addInfoSheet(wb, { title: 'Downstream Material Statement', period: data.period, generatedBy: user?.full_name });

  const headerSheet = wb.addWorksheet('Statement Header');
  headerSheet.columns = [{ width: 26 }, { width: 48 }];
  [
    ['Period', `${data.period.from} - ${data.period.to}`],
    ['Sender', data.supplier?.name || '—'],
    ['Eural Code', data.material?.eural_code || '—'],
    ['WEEE Category', data.material?.weee_category || '—'],
    ['Material', data.material?.name_en || '—'],
    ['Quantity in kg', formatWeight(data.totalMaterialKg)],
    ['Process Description', data.processDescription || '—'],
  ].forEach((row) => headerSheet.addRow(row));

  const ws = wb.addWorksheet('Fractions');
  ws.columns = [
    { header: 'Fractions', key: 'fractionName', width: 24 },
    { header: 'Eural Code', key: 'euralCode', width: 14 },
    { header: '%', key: 'sharePct', width: 10 },
    { header: 'First acceptant / Following', key: 'acceptantDisplay', width: 28 },
    { header: 'Process Description', key: 'processDescription', width: 34 },
    { header: '% Prepared for re-use', key: 'preparedForReusePct', width: 16 },
    { header: '% Recycling', key: 'recyclingPct', width: 14 },
    { header: '% Other material recovery', key: 'otherMaterialRecoveryPct', width: 18 },
    { header: '% Energy Recovery', key: 'energyRecoveryPct', width: 16 },
    { header: '% Thermal Disposal', key: 'thermalDisposalPct', width: 16 },
    { header: '% Landfill Disposal', key: 'landfillDisposalPct', width: 16 },
  ];
  styleHeaderRow(ws, 1);
  let rowNum = 2;
  for (const row of data.rows) {
    ws.addRow({
      fractionName: row.fractionName,
      euralCode: row.euralCode,
      sharePct: formatPct(row.sharePct),
      acceptantDisplay: row.acceptantDisplay,
      processDescription: row.processDescription,
      preparedForReusePct: formatPct(row.preparedForReusePct),
      recyclingPct: formatPct(row.recyclingPct),
      otherMaterialRecoveryPct: formatPct(row.otherMaterialRecoveryPct),
      energyRecoveryPct: formatPct(row.energyRecoveryPct),
      thermalDisposalPct: formatPct(row.thermalDisposalPct),
      landfillDisposalPct: formatPct(row.landfillDisposalPct),
    });
    styleDataRow(ws, rowNum++);
  }

  await wb.xlsx.writeFile(filePath);
}

module.exports = {
  generateSupplierStatementXLSX,
  generateMaterialRecoveryXLSX,
  generateChainOfCustodyXLSX,
  generateInboundWeightRegisterXLSX,
  generateWasteStreamAnalysisXLSX,
  generateAssetUtilisationXLSX,
  generateDownstreamStatementXLSX,
};
